version: '3.8'

services:
  puppet:
    image: puppet
    build:
      context: .
      dockerfile: Dockerfile
    container_name: puppeteer-utils
    ports:
      - "9222:9223"
    volumes:
      - ./profile:/app/profile
      - ./screenshots:/app/screenshots
      - ./.env:/app/.env
    stdin_open: true
    tty: true
